### ISSUE TITLE
Issue on download the dataset

### ISSUE THREAD

**Issue by dhhien1503** [gegewen/ufno#2]
Hi Gege,

Thank you for sharing us very interesting UFNO algorithm and its implementation for a very challenging CO2 injection and storage problem. I tried to understand the method via the example that you made it however I have a problem on downloading the large dataset (92GB) from your google drive. Can you please let me know the alternative way to download it e.g. via linux command windows software. 

Additionally, if we want to simulate our gas production simulation using Eclipse E300, can you please let me know the step by step to generate the dataset for training (create a *.pt file).

Thank you very much for your kind supports,
Best regards,
Hien

**Comment by gegewen** [comment]
Hi Hien,

For linux, you can use rclone to download the dataset. 
To generate the dataset, the paper includes a detailed description of each layer. However, I am unable to share the code for that due to proprietary reasons.

Hope this helps!
Best,
Gege
