### ISSUE TITLE
A question on the SpectralConv3d class

### ISSUE THREAD

**Issue by daniel-1388** [gegewen/ufno#3]
Hi
I have a question. Why do you perform the Fourier transform partly (boxes in the corners), like below. Why not to take the whole array?

Best regards,

        out_ft[:, :, :self.modes1, :self.modes2, :self.modes3] = \
            self.compl_mul3d(x_ft[:, :, :self.modes1, :self.modes2, :self.modes3], self.weights1)
        
        out_ft[:, :, -self.modes1:, :self.modes2, :self.modes3] = \
            self.compl_mul3d(x_ft[:, :, -self.modes1:, :self.modes2, :self.modes3], self.weights2)
        
        out_ft[:, :, :self.modes1, -self.modes2:, :self.modes3] = \
            self.compl_mul3d(x_ft[:, :, :self.modes1, -self.modes2:, :self.modes3], self.weights3)
        
        out_ft[:, :, -self.modes1:, -self.modes2:, :self.modes3] = \
            self.compl_mul3d(x_ft[:, :, -self.modes1:, -self.modes2:, :self.modes3], self.weights4)

**Comment by gegewen** [comment]
Hi, we computed the Fourier transform with the entire domain but calculated the weights in the boxes in the corners. By using this technique, we filtered out the high frequencies to improve computational efficiency and reduced overfitting.

**Comment by daniel-1388** [comment]
Hi, so the boxes are to keep only the low frequency modes, but they don't have to be at the corners correct?

**Comment by gegewen** [comment]
This is because fft in pytorch automatically place the lower frequency modes on the corners

**Comment by daniel-1388** [comment]
Indeed, I just read about this in the numpy.fft
Thanks a lot for clearing things out :)
